apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: talhatabrezm/health-backend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8010
          env:
            - name: DB_HOST
              value: "db"
            - name: DB_USER
              value: "root"
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: mysql-root-password
            - name: DB_NAME
              value: "HEALTH_DB"
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  type: ClusterIP
  ports:
    - port: 8010
      targetPort: 8010
  selector:
    app: backend