CREATE DATABASE IF NOT EXISTS HEALTH_DB;

USE HEALTH_DB;

CREATE TABLE IF NOT EXISTS SERVICES (
    ID INT AUTO_INCREMENT PRIMARY KEY, 
    NAME VARCHAR(255) NOT NULL, 
    ENDPOINT VARCHAR(255) NOT NULL, 
    STATUS VARCHAR(255) DEFAULT 'HEALTHY',
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO SERVICES( NAME, ENDPOINT, STATUS ) VALUES ( 'AUTHSERVICE', 'HTTPS://AUTH.API', 'HEALTHY');